[package]
name = "exc-core"
version = "0.4.9"
edition = "2021"
authors = ["Nouzan <clobraindie@outlook.com>"]
license = "MIT"
readme = "README.md"
description = "Abstractions of exchanges."
repository = "https://github.com/Nouzan/exc"
keywords = ["exchange", "tower"]

[features]
default = ["websocket", "http", "retry"]
websocket = [
    "tokio-tungstenite",
    "dep:http",
    "tokio/net",
]
driven = ["tokio/sync", "tokio/rt", "pin-project-lite"]
http = ["hyper/client", "hyper/http1", "hyper-tls", "dep:http"]
retry = ["tower/retry", "tokio/time", "humantime"]

[dependencies]
anyhow = "1"
thiserror = "1.0.30"
tracing = "0.1.34"
tower = { version = "0.4.12", features = ["util", "buffer", "limit", "ready-cache"] }
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
time = { version = "0.3.9", features = ["serde-well-known", "macros"] }
rust_decimal = "1.23.1"
indicator = "0.2"
derive_more = "0.99"
async-stream = "0.3"
num-traits = "0.2.15"
positions = "0.1"
either = "1"
tokio-stream = "0.1.9"
humantime = { version = "2.1.0", optional = true }

[dependencies.tokio-tungstenite]
version = "0.17.1"
features = ["native-tls"]
optional = true

[dependencies.http]
version = "0.2.6"
optional = true

[dependencies.tokio]
version = "1.17.0"
optional = true

[dependencies.pin-project-lite]
version = "0.2.7"
optional = true

[dependencies.hyper]
version = "0.14"
optional = true

[dependencies.hyper-tls]
version = "0.5"
optional = true

# dev
[dev-dependencies]
exc = { path = "../exc"}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
