[package]
name = "exc"
version = "0.4.9"
edition = "2021"
authors = ["Nouzan <clobraindie@outlook.com>"]
license = "MIT"
readme = "README.md"
description = "Abstractions of exchanges."
repository = "https://github.com/Nouzan/exc"
keywords = ["exchange", "tower"]

[features]
okx = ["exc-okx"]
binance = ["exc-binance"]
websocket = ["exc-core/websocket"]
driven = ["exc-core/driven"]
http = ["exc-core/http"]
retry = ["exc-core/retry"]

[dependencies]
exc-core = { version = "0.4.9", path = "../exc-core" }
tracing = "0.1.34"
tower = { version = "0.4.13" }
futures = { version = "0.3.21"}
async-stream = "0.3"
time = { version = "0.3.9", features = ["serde-well-known", "macros"] }
tokio-stream = "0.1.9"
rust_decimal = "1.25.0"
either = "1.6.1"

exc-okx = { version = "0.4.9", path = "../exc-okx", optional = true}
exc-binance = { version = "0.4.9", path = "../exc-binance", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
