[package]
name = "exc"
version = "0.1.0-alpha.3"
edition = "2021"
authors = ["Nouzan <clobraindie@outlook.com>"]
license = "MIT"
description = "Abstractions of exchanges."
repository = "https://github.com/Nouzan/exc"
keywords = ["exchange", "tower"]

[features]
websocket = [
    "tokio-tungstenite",
    "dep:http",
    "tokio/net",
]
driven = ["tokio/sync", "tokio/rt", "tokio-stream", "pin-project-lite"]
http = ["hyper/client", "hyper/http1", "hyper-tls", "dep:http"]

[dependencies]
anyhow = "1"
thiserror = "1.0.30"
tracing = "0.1.34"
tower = { version = "0.4.12", features = ["util"] }
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
time = { version = "0.3.9", features = ["serde-well-known"] }
rust_decimal = "1.23.1"
indicator = "0.2"

[dependencies.tokio-tungstenite]
version = "0.17.1"
features = ["native-tls"]
optional = true

[dependencies.http]
version = "0.2.6"
optional = true

[dependencies.tokio]
version = "1.17.0"
optional = true

[dependencies.tokio-stream]
version = "0.1.8"
optional = true

[dependencies.pin-project-lite]
version = "0.2.7"
optional = true

[dependencies.hyper]
version = "0.14"
optional = true

[dependencies.hyper-tls]
version = "0.5"
optional = true
