[package]
name = "exc"
version = "0.0.0"
edition = "2021"
authors = ["Nouzan <clobraindie@outlook.com>"]
license = "MIT"
description = "Abstractions of exchanges."
repository = "https://github.com/Nouzan/exc"
keywords = ["exchange", "tower"]

[dependencies]
thiserror = "1.0.30"
tracing = "0.1.34"
tower-service = "0.3.1"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
time = { version = "0.3.9", features = ["serde-well-known"] }
rust_decimal = "1.23.1"
