[workspace]
members = [
    "exc-core",
    "exc",
    "exc-okx",
    "exc-binance",
    "examples",
]

[workspace.package]
version = "0.5.0"
edition = "2021"
authors = ["Nouzan <clobraindie@outlook.com>"]
license = "MIT"
repository = "https://github.com/Nouzan/exc"
keywords = ["exchange", "tower"]
readme = "README.md"
description = "Abstractions of exchanges."
rust-version = "1.64"

[workspace.dependencies]
exc-core = { version = "0.5", path = "./exc-core" }
exc-binance = { version = "0.5", path = "./exc-binance" }
exc-okx = { version = "0.5", path = "./exc-okx" }
exc = { version = "0.5", path = "./exc" }
