[package]
name = "exchange"
version = "0.1.0"
edition = "2021"
authors = ["Nouzan <clobraindie@outlook.com>"]
license = "MIT"
description = "Abstractions of exchanges."
repository = "https://github.com/Nouzan/indicator"
keywords = ["exchange", "tower"]

[dependencies]
