[package]
name = "exc"
version = "0.0.0"
edition = "2021"
authors = ["Nouzan <clobraindie@outlook.com>"]
license = "MIT"
description = "Abstractions of exchanges."
repository = "https://github.com/Nouzan/exc"
keywords = ["exchange", "tower"]

[dependencies]
