[package]
name = "exc-examples"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "basic-okx"
path = "basic_okx.rs"

[[bin]]
name = "okx-two-streams"
path = "okx_two_streams.rs"

[dependencies]
anyhow = "1"
exc = { path = "../exc" }
exc-okx = { path = "../exc-okx" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
futures = "0.3.21"
tower = "0.4.12"
