[package]
name = "exc-examples"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "okx-instrument"
path = "okx_instrument.rs"

[[bin]]
name = "okx-ws-basic"
path = "okx_ws_basic.rs"

[[bin]]
name = "okx-http-basic"
path = "okx_http_basic.rs"

[[bin]]
name = "okx-two-streams"
path = "okx_two_streams.rs"

[[bin]]
name = "okx-candle"
path = "okx_candle.rs"

[dependencies]
anyhow = "1"
exc = { path = "../exc", features = ["http"] }
exc-okx = { path = "../exc-okx" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
futures = "0.3.21"
tower = { version = "0.4.12", features = ["util", "limit", "buffer", "retry"] }
time = { version = "0.3", features = ["macros"] }
