[package]
name = "exc-okx"
version = "0.1.0"
edition = "2021"
authors = ["Nouzan <clobraindie@outlook.com>"]
license = "MIT"
description = "OKX exchange services"
repository = "https://github.com/Nouzan/exc"
keywords = ["exchange", "tower", "okx"]

[dependencies.exc]
path = "../exc"
features = ["websocket"]

[dependencies.http]
version = "0.2.6"

[dependencies.thiserror]
version = "1.0.30"

[dependencies.tower]
version = "0.4.12"
features = ["util", "reconnect"]

[dependencies.tokio-tungstenite]
version = "0.17.1"
features = ["native-tls"]

[dependencies.futures]
version = "0.3.21"
